# Generated by Django 5.1.2 on 2025-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
